FROM node:22-alpine

WORKDIR /app

# Package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Prisma files
COPY prisma ./prisma
COPY prisma.config.js ./

# Generate Prisma Client
RUN npx prisma generate

# Application source
COPY src ./src

ENV NODE_ENV=production

EXPOSE 5000

CMD ["npm", "start"]