FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma
COPY prisma.config.js ./
COPY src ./src

RUN npx prisma generate

RUN test -f src/generated/prisma/client.js

ENV NODE_ENV=production

EXPOSE 5000

CMD ["npm", "start"]